services:
  postgres:
    image: postgres:16-alpine
    container_name: robot_dog_db
    restart: unless-stopped

    environment:
      POSTGRES_USER: robot
      POSTGRES_PASSWORD: robot_password
      POSTGRES_DB: robot_dog

    ports:
      - '5432:5432'

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U robot']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
