services:
  postgres:
    image: postgres:16-alpine
    container_name: robot_dog_db
    restart: unless-stopped

    environment:
      POSTGRES_USER: robot
      POSTGRES_PASSWORD: robot_password
      POSTGRES_DB: robot_dog

    ports:
      - '5432:5432'

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U robot']
      interval: 5s
      timeout: 5s
      retries: 5

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: robot_dog_mqtt
    restart: unless-stopped
    ports:
      - '1883:1883'
      - '8883:8883'
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/passwordfile:/mosquitto/config/passwordfile
      - ./mosquitto/aclfile:/mosquitto/config/aclfile
      - ./mosquitto/certs:/mosquitto/certs
      - mosquitto_data:/mosquitto/data
      - mosquitto_logs:/mosquitto/log

  redis:
    image: redis:7-alpine
    container_name: robot_dog_redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 3s
      retries: 5

  rabbitmq:
    image: rabbitmq:4-management-alpine
    container_name: robot_dog_rabbitmq
    restart: unless-stopped
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: doggo
      RABBITMQ_DEFAULT_PASS: doggo_password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ['CMD', 'rabbitmq-diagnostics', 'ping']
      interval: 5s
      timeout: 5s
      retries: 5

  worker:
    build: ../worker
    container_name: robot_dog_mission_report_worker
    restart: unless-stopped
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: doggo
      RABBITMQ_PASSWORD: doggo_password
      GCS_BUCKET_NAME: doggo-mission-reports
      GOOGLE_APPLICATION_CREDENTIALS: /secrets/gcs-worker-key.json
    volumes:
      - ./worker-secrets/gcs-worker-key.json:/secrets/gcs-worker-key.json:ro

volumes:
  postgres_data:
  mosquitto_data:
  mosquitto_logs:
  redis_data:
  rabbitmq_data:
